# Generated by Django 3.0.2 on 2021-02-25 16:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('with_extra_from_to', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('column_separator_type', models.CharField(choices=[('CM', 'Comma (,)'), ('SM', 'Semicolon (;)'), ('TB', 'Tab (\\t)'), ('PP', 'Pipe (|)')], db_index=True, default='CM', max_length=2)),
                ('string_character_type', models.CharField(choices=[('DQ', 'Double quote (")'), ('SQ', "Single quote (')")], db_index=True, default='DQ', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('RD', 'Ready'), ('PR', 'Processing')], db_index=True, default='PR', max_length=2)),
                ('file', models.FileField(blank=True, upload_to='schemas/%Y/%m/%d')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('schema', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schemas.Schema')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('with_extra_from_to', models.BooleanField(default=False)),
                ('extra_from', models.PositiveIntegerField(blank=True)),
                ('extra_to', models.PositiveIntegerField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schemas.ColumnTypes')),
            ],
        ),
    ]
